// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcMSkAzh0xHcosFuJkdms1kDTx2eY3jxI',
    appId: '1:359951087284:web:385712213bfa2d027109e1',
    messagingSenderId: '359951087284',
    projectId: 'genuno-f6ce8',
    authDomain: 'genuno-f6ce8.firebaseapp.com',
    databaseURL: 'https://genuno-f6ce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'genuno-f6ce8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCid1yvVTKELTXl2ksDBeNWB1bhhm7PjCg',
    appId: '1:359951087284:android:bf9cb14ac6c1e0a27109e1',
    messagingSenderId: '359951087284',
    projectId: 'genuno-f6ce8',
    databaseURL: 'https://genuno-f6ce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'genuno-f6ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdgkWF3PhR0UIwprbg5Afsj4Pl0JBcqpk',
    appId: '1:359951087284:ios:18611fb6def58e1c7109e1',
    messagingSenderId: '359951087284',
    projectId: 'genuno-f6ce8',
    databaseURL: 'https://genuno-f6ce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'genuno-f6ce8.appspot.com',
    iosBundleId: 'com.example.genunoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdgkWF3PhR0UIwprbg5Afsj4Pl0JBcqpk',
    appId: '1:359951087284:ios:edf73f14910fa2fa7109e1',
    messagingSenderId: '359951087284',
    projectId: 'genuno-f6ce8',
    databaseURL: 'https://genuno-f6ce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'genuno-f6ce8.appspot.com',
    iosBundleId: 'com.example.genunoFlutter.RunnerTests',
  );
}
